# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-31 10:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0004_auto_20171031_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='switch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asset.NetworkDevice', verbose_name='关联设备'),
        ),
        migrations.AlterField(
            model_name='networkdevice',
            name='intranet_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='管理IP'),
        ),
    ]
