# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-31 10:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0005_auto_20171031_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='switch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asset.NetworkDevice', verbose_name='所属网络设备'),
        ),
        migrations.AlterField(
            model_name='server',
            name='upper_layer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='upperlayer', to='asset.Server', verbose_name='上层设备'),
        ),
    ]
