# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-31 11:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0006_auto_20171031_1828'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cpu',
            old_name='asset',
            new_name='server',
        ),
        migrations.RenameField(
            model_name='disk',
            old_name='asset',
            new_name='server',
        ),
        migrations.RenameField(
            model_name='mem',
            old_name='asset',
            new_name='server',
        ),
        migrations.RenameField(
            model_name='nic',
            old_name='asset',
            new_name='server',
        ),
        migrations.RenameField(
            model_name='server',
            old_name='sub_asset_type',
            new_name='server_type',
        ),
        migrations.AlterUniqueTogether(
            name='mem',
            unique_together=set([]),
        ),
    ]
