# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-01 05:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0009_auto_20171101_1044'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('device_type_id', models.IntegerField(choices=[(1, '服务器'), (2, '交换机'), (3, '防火墙')], default=1)),
                ('device_status_id', models.IntegerField(choices=[(0, '在线'), (1, '已下线'), (2, '未知'), (3, '故障'), (4, '备用')], default=1)),
                ('cabinet_num', models.CharField(blank=True, max_length=30, null=True, verbose_name='机柜位')),
                ('business_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asset.BusinessUnit', verbose_name='属于的业务线')),
                ('idc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.IDC', verbose_name='IDC机房')),
                ('tag', models.ManyToManyField(to='asset.Tag')),
            ],
            options={
                'verbose_name_plural': '资产表',
            },
        ),
        migrations.RemoveField(
            model_name='networkdevice',
            name='network_device_type',
        ),
        migrations.RemoveField(
            model_name='server',
            name='business_unit',
        ),
        migrations.RemoveField(
            model_name='server',
            name='idc',
        ),
        migrations.RemoveField(
            model_name='server',
            name='status',
        ),
        migrations.AlterField(
            model_name='cpu',
            name='speed',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='CPU主频（MHz）'),
        ),
        migrations.AlterField(
            model_name='server',
            name='switch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asset.NetworkDevice', verbose_name='交换机接口'),
        ),
        migrations.AlterField(
            model_name='server',
            name='upper_layer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='upperlayer', to='asset.Server', verbose_name='所属宿主机'),
        ),
        migrations.AddField(
            model_name='networkdevice',
            name='asset',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asset.Asset', verbose_name='资产'),
        ),
        migrations.AddField(
            model_name='server',
            name='asset',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asset.Asset', verbose_name='资产'),
        ),
    ]
