# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-05 13:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0012_auto_20171105_2148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='idc',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='tag',
        ),
        migrations.AddField(
            model_name='idc',
            name='cabinet_num',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='机柜位'),
        ),
        migrations.AddField(
            model_name='idc',
            name='device_status_id',
            field=models.IntegerField(choices=[(0, '在线'), (1, '已下线'), (2, '未知'), (3, '故障'), (4, '备用')], default=1),
        ),
        migrations.AddField(
            model_name='idc',
            name='device_type_id',
            field=models.IntegerField(choices=[(1, '服务器'), (2, '交换机'), (3, '防火墙')], default=1),
        ),
        migrations.AddField(
            model_name='idc',
            name='tag',
            field=models.ManyToManyField(blank=True, default=1, to='asset.Tag'),
        ),
        migrations.AlterField(
            model_name='networkdevice',
            name='asset',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asset.IDC', verbose_name='资产'),
        ),
        migrations.AlterField(
            model_name='server',
            name='asset',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asset.IDC', verbose_name='资产'),
        ),
        migrations.DeleteModel(
            name='Asset',
        ),
    ]
