# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-05 13:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0013_auto_20171105_2155'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('device_type_id', models.IntegerField(choices=[(1, '服务器'), (2, '交换机'), (3, '防火墙')], default=1)),
                ('device_status_id', models.IntegerField(choices=[(0, '在线'), (1, '已下线'), (2, '未知'), (3, '故障'), (4, '备用')], default=1)),
                ('cabinet_num', models.CharField(blank=True, max_length=30, null=True, verbose_name='机柜位')),
            ],
            options={
                'verbose_name_plural': '资产表',
            },
        ),
        migrations.RemoveField(
            model_name='idc',
            name='cabinet_num',
        ),
        migrations.RemoveField(
            model_name='idc',
            name='device_status_id',
        ),
        migrations.RemoveField(
            model_name='idc',
            name='device_type_id',
        ),
        migrations.RemoveField(
            model_name='idc',
            name='tag',
        ),
        migrations.AlterField(
            model_name='networkdevice',
            name='asset',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asset.Asset', verbose_name='资产'),
        ),
        migrations.AlterField(
            model_name='server',
            name='asset',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asset.Asset', verbose_name='资产'),
        ),
        migrations.AddField(
            model_name='asset',
            name='idc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.IDC', verbose_name='IDC机房'),
        ),
        migrations.AddField(
            model_name='asset',
            name='tag',
            field=models.ManyToManyField(blank=True, default=1, to='asset.Tag'),
        ),
    ]
