# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-10 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0016_auto_20171110_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device_Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': '设备状态',
                'verbose_name': '设备状态',
            },
        ),
    ]
