# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-10 08:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0017_device_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device_status',
            old_name='status',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='server',
            name='device_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='asset.Device_Status', verbose_name='设备状态'),
        ),
    ]
