# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-13 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0021_auto_20171113_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='name',
            field=models.CharField(default=1, max_length=18, unique=True, verbose_name='主机名'),
            preserve_default=False,
        ),
    ]
