# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-15 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0022_auto_20171113_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='expire_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='过保修期'),
        ),
        migrations.AlterField(
            model_name='server',
            name='trade_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='购买时间'),
        ),
    ]
