# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-15 16:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0024_auto_20171115_2351'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cabinet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('device_type_id', models.IntegerField(choices=[(1, '服务器'), (2, '交换机'), (3, '防火墙')], default=1, verbose_name='设备类型')),
                ('cabinet_num', models.CharField(blank=True, max_length=30, null=True, verbose_name='机柜位')),
                ('idc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.IDC', verbose_name='IDC机房')),
                ('tag', models.ManyToManyField(blank=True, default=1, to='asset.Tag')),
            ],
            options={
                'verbose_name_plural': '机柜信息',
            },
        ),
        migrations.RemoveField(
            model_name='asset',
            name='idc',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='tag',
        ),
        migrations.DeleteModel(
            name='Device_Status',
        ),
        migrations.AlterField(
            model_name='networkdevice',
            name='asset',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asset.Cabinet', verbose_name='资产'),
        ),
        migrations.AlterField(
            model_name='server',
            name='asset',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asset.Cabinet', verbose_name='资产'),
        ),
        migrations.DeleteModel(
            name='Asset',
        ),
    ]
