# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-16 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0026_auto_20171116_0125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cabinet',
            name='tag',
        ),
        migrations.AddField(
            model_name='cabinet',
            name='memo',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='备注'),
        ),
    ]
