# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-16 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0027_auto_20171116_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabinet',
            name='memo',
            field=models.TextField(blank=True, max_length=128, null=True, verbose_name='备注'),
        ),
    ]
