# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-12 16:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0029_auto_20171118_0026'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businessunit',
            options={'ordering': ['name'], 'verbose_name': '业务线', 'verbose_name_plural': '业务线'},
        ),
        migrations.AlterField(
            model_name='businessunit',
            name='parent_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_level', to='asset.BusinessUnit', verbose_name='上层模块'),
        ),
        migrations.AlterField(
            model_name='networkdevice',
            name='cabinet',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asset.Cabinet', verbose_name='机柜信息'),
        ),
        migrations.AlterField(
            model_name='networkdevice',
            name='device_detail',
            field=models.TextField(blank=True, null=True, verbose_name='配置'),
        ),
        migrations.AlterField(
            model_name='networkdevice',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='设备名称'),
        ),
        migrations.AlterField(
            model_name='server',
            name='cabinet',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asset.Cabinet', verbose_name='机柜信息'),
        ),
        migrations.AlterField(
            model_name='server',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='主机名'),
        ),
    ]
