# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-27 12:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0031_auto_20171217_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mem',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mem', to='asset.Server', verbose_name='所属服务器'),
        ),
        migrations.AlterField(
            model_name='server',
            name='cabinet',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cabinet', to='asset.Cabinet', verbose_name='机柜位置'),
        ),
    ]
