# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-02 06:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0035_auto_20180101_1723'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOwnedHost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.ManyToManyField(to='asset.Server', verbose_name='主机')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.User', verbose_name='用户')),
            ],
        ),
    ]
