# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-14 06:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0037_auto_20180102_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='host',
        ),
        migrations.AddField(
            model_name='user',
            name='businessunit',
            field=models.ManyToManyField(related_name='businessunit', to='asset.BusinessUnit', verbose_name='业务分组'),
        ),
    ]
